// Code generated by MockGen. DO NOT EDIT.
// Source: client_info.go

// Package service_mock is a generated GoMock package.
package service_mock

import (
	ctm_err "go-auth-bl/pkg/error"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIClientInfoService is a mock of IClientInfoService interface.
type MockIClientInfoService struct {
	ctrl     *gomock.Controller
	recorder *MockIClientInfoServiceMockRecorder
}

// MockIClientInfoServiceMockRecorder is the mock recorder for MockIClientInfoService.
type MockIClientInfoServiceMockRecorder struct {
	mock *MockIClientInfoService
}

// NewMockIClientInfoService creates a new mock instance.
func NewMockIClientInfoService(ctrl *gomock.Controller) *MockIClientInfoService {
	mock := &MockIClientInfoService{ctrl: ctrl}
	mock.recorder = &MockIClientInfoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIClientInfoService) EXPECT() *MockIClientInfoServiceMockRecorder {
	return m.recorder
}

// IsEnableClient mocks base method.
func (m *MockIClientInfoService) IsEnableClient(clientId, redirectUri string) *ctm_err.CustomError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEnableClient", clientId, redirectUri)
	ret0, _ := ret[0].(*ctm_err.CustomError)
	return ret0
}

// IsEnableClient indicates an expected call of IsEnableClient.
func (mr *MockIClientInfoServiceMockRecorder) IsEnableClient(clientId, redirectUri interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEnableClient", reflect.TypeOf((*MockIClientInfoService)(nil).IsEnableClient), clientId, redirectUri)
}
